title: Sysctl Explorer
author: Pierre Roudier
email: sysctl-explorer@gmail.com
description: "Painless access to Linux sysctl reference documentation"
url: "https://sysctl-explorer.net"
baseurl: "" # the subpath of your site, e.g. /blog

last-db-update: 2018-12-09 18:93:01 UTC

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-minifier
  - jekyll-sitemap

exclude:
  - .idea

sass:
  style: compressed

defaults:
  -
    scope:
      path: "fs"
    values:
      permalink: /:path/:basename/
  -
    scope:
      path: "kernel"
    values:
      permalink: /:path/:basename/
  -
    scope:
      path: "net"
    values:
      permalink: /:path/:basename/
  -
    scope:
      path: "vm"
    values:
      permalink: /:path/:basename/

algolia:
  application_id: GOBDHY63K2
  index_name: sysctl-explorer
  search_only_api_key: 5a2c0202b889e92cb65433bc586daef4