title: Sysctl Explorer
author: Pierre Roudier
email: sysctl-explorer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: "https://sysctl-explorer.net"
baseurl: "" # the subpath of your site, e.g. /blog

last-db-update: 2018-12-09 18:93:01 UTC

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-minifier
  - jekyll-sitemap

exclude:
  - .idea

sass:
  style: compressed
